language: java
jdk:
 - oraclejdk8
cache:
  directores:
    - $HOME/.gradle
    - .gradle
script:
  - ./gradlew build
deploy:
 provider: heroku
 skip_cleanup: true
 api-key:
  secure: $HEROKU_API_KEY
 app: commerce-jakubopgk
 branch: develop
 on:
     branch: develop